CREATE TABLE food_catalog (
    id VARCHAR(80) PRIMARY KEY,
    search_text TEXT NOT NULL,
    revision VARCHAR(64) NOT NULL,
    payload TEXT NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE food_catalog_lock (id INTEGER PRIMARY KEY);
INSERT INTO food_catalog_lock(id) VALUES(1);
ALTER TABLE foods ADD COLUMN source VARCHAR(20) NOT NULL DEFAULT 'USER_ENTERED';
ALTER TABLE meal_record_items ADD COLUMN source VARCHAR(20) NOT NULL DEFAULT 'USER_ENTERED';
