CREATE TABLE user_profile_revisions (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL,
    revision BIGINT NOT NULL,
    effective_from DATE NOT NULL,
    age INTEGER NOT NULL,
    sex VARCHAR(16) NOT NULL,
    height_cm NUMERIC(5, 2) NOT NULL,
    initial_weight_kg NUMERIC(7, 3) NOT NULL,
    initial_waist_cm NUMERIC(6, 2),
    goal VARCHAR(16) NOT NULL,
    target_weight_kg NUMERIC(7, 3),
    activity_level VARCHAR(16) NOT NULL,
    exercise_days VARCHAR(13) NOT NULL,
    exercise_minutes INTEGER NOT NULL,
    experience VARCHAR(16) NOT NULL,
    units VARCHAR(16) NOT NULL,
    nutrition_mode VARCHAR(16) NOT NULL,
    daily_calories INTEGER,
    carbohydrate_g NUMERIC(7, 2),
    protein_g NUMERIC(7, 2),
    fat_g NUMERIC(7, 2),
    fiber_g NUMERIC(7, 2),
    recent_exercise_days INTEGER,
    recent_exercise_minutes INTEGER,
    recent_exercise_type VARCHAR(16) NOT NULL,
    recent_exercise_intensity VARCHAR(16) NOT NULL,
    schedule_flexible BOOLEAN NOT NULL,
    weekly_frequency INTEGER NOT NULL,
    target_formula_version VARCHAR(64),
    terms_version VARCHAR(32) NOT NULL,
    privacy_version VARCHAR(32) NOT NULL,
    health_consent_version VARCHAR(32) NOT NULL,
    time_zone VARCHAR(64) NOT NULL,
    accepted_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_profile_user FOREIGN KEY (user_id) REFERENCES user_accounts (id) ON DELETE CASCADE,
    CONSTRAINT uq_profile_user_revision UNIQUE (user_id, revision),
    CONSTRAINT ck_profile_revision CHECK (revision >= 0),
    CONSTRAINT ck_profile_age CHECK (age BETWEEN 19 AND 120),
    CONSTRAINT ck_profile_sex CHECK (sex IN ('MALE', 'FEMALE', 'UNSPECIFIED')),
    CONSTRAINT ck_profile_height CHECK (height_cm > 0 AND height_cm <= 300),
    CONSTRAINT ck_profile_weight CHECK (initial_weight_kg > 0 AND initial_weight_kg <= 1000),
    CONSTRAINT ck_profile_waist CHECK (initial_waist_cm IS NULL OR (initial_waist_cm > 0 AND initial_waist_cm <= 500)),
    CONSTRAINT ck_profile_target_weight CHECK (target_weight_kg IS NULL OR (target_weight_kg > 0 AND target_weight_kg <= 1000)),
    CONSTRAINT ck_profile_goal CHECK (goal IN ('MAINTAIN', 'GAIN', 'LOSE')),
    CONSTRAINT ck_profile_activity CHECK (activity_level IN ('SEDENTARY', 'LIGHT', 'MODERATE', 'HIGH')),
    CONSTRAINT ck_profile_minutes CHECK (exercise_minutes BETWEEN 0 AND 1440),
    CONSTRAINT ck_profile_experience CHECK (experience IN ('BEGINNER', 'INTERMEDIATE', 'ADVANCED')),
    CONSTRAINT ck_profile_units CHECK (units IN ('METRIC', 'IMPERIAL')),
    CONSTRAINT ck_profile_mode CHECK (nutrition_mode IN ('AUTO', 'BODY_WEIGHT', 'MANUAL', 'NONE')),
    CONSTRAINT ck_profile_calories CHECK (daily_calories > 0 AND daily_calories <= 50000),
    CONSTRAINT ck_profile_nutrients CHECK (carbohydrate_g BETWEEN 0 AND 10000 AND protein_g BETWEEN 0 AND 10000 AND fat_g BETWEEN 0 AND 10000 AND fiber_g BETWEEN 0 AND 10000),
    CONSTRAINT ck_profile_nutrition_presence CHECK (
        (nutrition_mode = 'NONE' AND daily_calories IS NULL AND carbohydrate_g IS NULL AND protein_g IS NULL AND fat_g IS NULL AND fiber_g IS NULL)
        OR (nutrition_mode <> 'NONE' AND daily_calories IS NOT NULL AND carbohydrate_g IS NOT NULL AND protein_g IS NOT NULL AND fat_g IS NOT NULL)
    ),
    CONSTRAINT ck_profile_recent_days CHECK (recent_exercise_days BETWEEN 0 AND 7),
    CONSTRAINT ck_profile_recent_minutes CHECK (recent_exercise_minutes BETWEEN 0 AND 1440),
    CONSTRAINT ck_profile_recent_type CHECK (recent_exercise_type IN ('STRENGTH', 'CARDIO', 'MIXED', 'UNKNOWN')),
    CONSTRAINT ck_profile_recent_intensity CHECK (recent_exercise_intensity IN ('LOW', 'MODERATE', 'HIGH', 'UNKNOWN')),
    CONSTRAINT ck_profile_frequency CHECK (weekly_frequency BETWEEN 0 AND 7)
);
CREATE INDEX ix_profile_user_effective ON user_profile_revisions (user_id, effective_from, revision);

ALTER TABLE body_measurements ADD COLUMN memo VARCHAR(1000);
