package com.bapegg.routinlog.ui

import com.bapegg.routinlog.R

// Lucide assets; license in assets/licenses.
val NativeIcons = mapOf(
    "Camera" to R.drawable.ic_camera,
    "Circle" to R.drawable.ic_circle,
    "ChevronRight" to R.drawable.ic_chevron_right,
    "ChevronLeft" to R.drawable.ic_chevron_left,
    "Check" to R.drawable.ic_check,
    "Minus" to R.drawable.ic_minus,
    "Plus" to R.drawable.ic_plus,
    "Package" to R.drawable.ic_package,
    "Wheat" to R.drawable.ic_wheat,
    "Utensils" to R.drawable.ic_utensils,
    "CookingPot" to R.drawable.ic_cooking_pot,
    "Salad" to R.drawable.ic_salad,
    "BottleWine" to R.drawable.ic_bottle_wine,
    "Milk" to R.drawable.ic_milk,
    "CircleCheck" to R.drawable.ic_circle_check,
    "CirclePlay" to R.drawable.ic_circle_play,
    "Scale" to R.drawable.ic_scale,
    "Footprints" to R.drawable.ic_footprints,
    "ChartNoAxesCombined" to R.drawable.ic_chart_no_axes_combined,
    "Clock3" to R.drawable.ic_clock3,
    "Repeat2" to R.drawable.ic_repeat2,
    "Dumbbell" to R.drawable.ic_dumbbell,
    "ArrowRight" to R.drawable.ic_arrow_right,
    "BookOpen" to R.drawable.ic_book_open,
    "House" to R.drawable.ic_house,
    "CalendarDays" to R.drawable.ic_calendar_days,
    "Settings" to R.drawable.ic_settings,
    "Signal" to R.drawable.ic_signal,
    "Wifi" to R.drawable.ic_wifi,
    "BatteryFull" to R.drawable.ic_battery_full,
    "X" to R.drawable.ic_x,
    "ArrowLeft" to R.drawable.ic_arrow_left,
    "Activity" to R.drawable.ic_activity,
    "ChevronDown" to R.drawable.ic_chevron_down,
    "ChevronUp" to R.drawable.ic_chevron_up,
    "Moon" to R.drawable.ic_moon,
    "HeartPulse" to R.drawable.ic_heart_pulse,
    "PencilLine" to R.drawable.ic_pencil_line,
    "MessageCircle" to R.drawable.ic_message_circle,
    "Settings2" to R.drawable.ic_settings_2,
    "Wind" to R.drawable.ic_wind,
    "Bell" to R.drawable.ic_bell,
    "UserRound" to R.drawable.ic_user_round,
    "ShieldCheck" to R.drawable.ic_shield_check,
    "LogOut" to R.drawable.ic_log_out,
    "Trash2" to R.drawable.ic_trash_2,
    "ClipboardList" to R.drawable.ic_clipboard_list,
    "WifiOff" to R.drawable.ic_wifi_off,
    "RefreshCw" to R.drawable.ic_refresh_cw
)
